name: Build Gatsby

on:
  push:
    branches:
      - gh-pages-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          npm ci --legacy-peer-deps
          npm run build

      - uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          token: ${{ secrets.SITE_DEPLOY_ACCESS_TOKEN }}
          branch: gh-pages
          folder: public